[package]
name = "premiere-hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"
rayon = "1.8"
clap = { version = "4.4", features = ["derive"] }
indicatif = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
flate2 = "1"
ctrlc = "3"
quick-xml = "0.31"
